### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tahaluindo** [bahyusanciko/ci-tiket#22]
tampilan di website
```An uncaught Exception was encountered
Type: Error

Message: Class 'Dotenv\Dotenv' not found

Filename: /home/root/jogja.id/application/config/hooks.php

Line Number: 7

Backtrace:

File: /home/root/jogja.id/index.php
Line: 315
Function: require_once```

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

# Load phpdotenv
$hook['pre_system'] = function() {
 $dotenv = Dotenv\Dotenv::create(APPPATH);
 $dotenv->load();
};
/*
| -------------------------------------------------------------------------
| Hooks
| -------------------------------------------------------------------------
| This file lets you define "hooks" to extend CI without hacking the core
| files.  Please see the user guide for info:
|
|	https://codeigniter.com/user_guide/general/hooks.html
|
*/

```

solusinya dung

**Comment by tahaluindo** [comment]
ok

**Comment by tahaluindo** [comment]
Message: Class 'Dotenv\Dotenv' not found

**Comment by bahyusanciko** [comment]
install composer dulu bro, terus pasang .env di application/.env ada example nya
